### ISSUE TITLE
Utilise FaweAPI

### ISSUE THREAD

**Issue by Pigalala** [Pigalala/TrackExchange#3]
This means that schematics can be pasted simultaneously and hopefully not make worldedit cry 🙏

**Comment by Makkuusen** [comment]
Maybe check if you somehow could make a dependency to FastAsyncWorldEdit and if they have any option to kinda steal their optimized way of dealing with schematics.

**Comment by Pigalala** [comment]
Seems like FAWE doesn't actually have an async method for pasting (unless im blind). The wiki says to just asynchronously call the operation methods sadly.

**Comment by Pigalala** [comment]
Wait, let me cook
